on:
  push:
    tags:
      - '*'

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun print-pdf.ts
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "CV.pdf"
          token: ${{ github.token }}
